### ISSUE TITLE
GoException: no routes for location: landing

### ISSUE THREAD

**Issue by alba4k** [RetroMusicPlayer/Paisa#390]
https://github.com/RetroMusicPlayer/Paisa/assets/84153269/905ee008-6d5e-4960-8b11-a5e240488f31

Don't think I need to explain this much. The app is simply unusable in 5.0.4 (The black screen is what appears when screen recording an authentication screen, not what I actually see)

**Comment by Nahid-S** [comment]
Can anyone revert changes but up the version so it takes the updates and data doesn't get lost

**Comment by ATamblingPoder** [comment]
I think the json format has been changed quite a bit so the previous data may not work

**Comment by cvg095** [comment]
Hi Is there any workaround on this? I don't want to lose my data

**Comment by alba4k** [comment]
Honestly have no idea

**Comment by cvg095** [comment]
> Honestly have no idea, not that I have found

Well all we can do is wait for the new version hopefully it would be fix.

**Comment by h4h13** [comment]
Hey I have pushed a build please check once in that

**Comment by alba4k** [comment]
ayo @h4h13 when did the linux build become a thing

love you for that! still won't probably use it tho, at least until cloud sync becomes a thing, if ever ;)

**Comment by alba4k** [comment]
@h4h13 5.0.6 :(


 ![Screenshot_20231122_205634_Paisa.jpg](https://github.com/RetroMusicPlayer/Paisa/assets/84153269/1949dc8a-a7e1-424e-8c8b-9b090d126c57)

**Comment by h4h13** [comment]
How are you getting this error

**Comment by alba4k** [comment]
same as in the video


opening the app and authenticating

**Comment by h4h13** [comment]
You have biometric enabled?

**Comment by alba4k** [comment]
I do

my best guess however is that if I didn't, I would immediately get the error

@Nahid-S @cvg095 hbu?

**Comment by h4h13** [comment]
Got it fixed the error

**Comment by alba4k** [comment]
@h4h13 maybe send an apk in pvt chat on telegram before pushing a release, just to be sure

should I dm you first?

**Comment by alba4k** [comment]
Yeah nvm I guess

It works now tho!

**Comment by deavmi** [comment]
I am still having this issue on latest version. I am not using auth but my screen opens to a blank white page OR the logo
